# Generated by Django 4.1.4 on 2023-02-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_news_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
    ]
