# Generated by Django 4.1.4 on 2023-02-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_remove_news_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
