# Generated by Django 4.1.4 on 2023-02-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0005_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='data',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
