# Generated by Django 4.1.4 on 2023-02-18 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0006_news_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
