# Generated by Django 4.1.4 on 2023-02-19 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0007_remove_news_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='quantity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
